const fs = require('fs');

const content = `'use client';

import { useState } from 'react';
import { Download } from 'lucide-react';

export default function DownloadPDF({ trip }) {
  const [loading, setLoading] = useState(false);

  async function handleDownload() {
    setLoading(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      const itinerary = typeof trip.itinerary === 'string' ? JSON.parse(trip.itinerary) : trip.itinerary;

      let y = 20;
      const pageH = doc.internal.pageSize.height;
      const margin = 15;
      const maxW = 180;

      function checkPage(needed) {
        if (y + (needed || 10) > pageH - 20) { doc.addPage(); y = 20; }
      }

      doc.setFillColor(79, 70, 229);
      doc.rect(0, 0, 210, 35, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('TripMind AI', margin, 15);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text('Your Personalized Travel Itinerary', margin, 25);

      y = 50;
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(trip.destination || 'Trip Itinerary', margin, y);
      y += 10;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text('Dates: ' + trip.startDate + ' to ' + trip.endDate, margin, y);
      y += 6;
      doc.text('Budget: ' + trip.budget, margin, y);
      y += 10;

      doc.setDrawColor(220, 220, 220);
      doc.line(margin, y, 195, y);
      y += 10;

      if (itinerary && itinerary.summary) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(80, 80, 80);
        const summaryLines = doc.splitTextToSize(itinerary.summary, maxW);
        doc.text(summaryLines, margin, y);
        y += summaryLines.length * 5 + 10;
      }

      if (itinerary && itinerary.days) {
        for (const day of itinerary.days) {
          checkPage(25);
          doc.setFillColor(238, 242, 255);
          doc.rect(margin - 2, y - 5, maxW + 4, 12, 'F');
          doc.setFontSize(12);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(79, 70, 229);
          doc.text('Day ' + day.day + ': ' + (day.title || ''), margin, y + 2);
          y += 14;

          if (day.schedule) {
            for (const item of day.schedule) {
              checkPage(15);
              doc.setFontSize(9);
              doc.setFont('helvetica', 'bold');
              doc.setTextColor(50, 50, 50);
              doc.text((item.time || '') + ' - ' + (item.activity || ''), margin + 3, y);
              y += 5;
              if (item.description) {
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(100, 100, 100);
                const lines = doc.splitTextToSize(item.description, maxW - 5);
                checkPage(lines.length * 4 + 4);
                doc.text(lines, margin + 3, y);
                y += lines.length * 4 + 3;
              }
            }
          }

          if (day.accommodation) {
            checkPage(15);
            y += 2;
            doc.setFontSize(9);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(180, 120, 0);
            doc.text('Hotel: ' + (day.accommodation.name || ''), margin, y);
            y += 10;
          }

          y += 5;
        }
      }

      doc.setFillColor(79, 70, 229);
      doc.rect(0, pageH - 15, 210, 15, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text('Generated by TripMind AI · tripmind-ai-kappa.vercel.app', 105, pageH - 6, { align: 'center' });

      doc.save('TripMind-' + (trip.destination || 'Itinerary') + '.pdf');
    } catch (err) {
      console.error('PDF error:', err);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <button
      onClick={handleDownload}
      disabled={loading}
      className="flex items-center gap-2 bg-gradient-to-r from-indigo-600 to-pink-600 text-white px-4 py-2 rounded-xl text-sm font-semibold hover:opacity-90 disabled:opacity-50 transition"
    >
      <Download size={16} />
      {loading ? 'Generating PDF...' : 'Download PDF'}
    </button>
  );
}
`;

fs.writeFileSync('components/DownloadPDF.tsx', content);
console.log('Done');